部分纠错： ./bls_blst.go:48:25: cannot use err (variable of type *blst.P2Affine) as error value in return statement: *blst.P2Affine does not implement error (missing method Error)